### ISSUE TITLE
Will you support GPU computing in the future?

### ISSUE THREAD

**Issue by TanookiToad** [JuliaData/JuliaDB.jl#314]
That's to say, like [cuDF](https://github.com/rapidsai/cudf) library in Python.

**Comment by jpsamaroo** [comment]
I think this is doable at least for `IndexedTable`s, since columns are typically concretely typed. We'd probably want to put the GPU kernels and relational logic into another reusable package, since that functionality could be useful for other table types. The hardest part will be optimizing the relational kernels for reasonable performance, while minimizing CPU <-> GPU transfers.

@maleadt @vchuravy
